### ISSUE TITLE
Has anything changed withing source file ?

### ISSUE THREAD

**Issue by mathias3** [bradleypallen/keras-quora-question-pairs#3]
I got this error message :
KeyError                                  Traceback (most recent call last)
<ipython-input-27-fbf22262ce45> in <module>()
     10     reader = csv.DictReader(csvfile, delimiter='\t')
     11     for row in reader:
---> 12         question1.append(row['text1'])
     13         question2.append(row['text2'])
     14         is_duplicate.append(row['duplicate'])

KeyError: 'text1'

**Comment by bradleypallen** [comment]
The use of text1, text2 and dupicate, as opposed to the correct question1, question2 and is_duplicate were due to a temporary change in the state of the source Quora data file early on in February. Fixed.
