### ISSUE TITLE
Is it matched with the following URL and which IDE you used pls?

### ISSUE THREAD

**Issue by MrKyaw** [bradleypallen/keras-quora-question-pairs#4]
Dear Bradley,

I am new to NLP, TensorFlow and DL using  Python.

The design and implementation matched with this https://www.kaggle.com/c/quora-question-pairs/data pls ?

I couldn't manage to find q1_train.npy, q2_train.npy, label_train.npy, word_embedding_matrix.npy and nb_words.json in your repository so pls advise me.

The error below seem like related to the above missing files

Processing quora_duplicate_questions.tsv
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-fbf22262ce45> in <module>()
     10     reader = csv.DictReader(csvfile, delimiter='\t')
     11     for row in reader:
---> 12         question1.append(row['text1'])
     13         question2.append(row['text2'])
     14         is_duplicate.append(row['duplicate'])

KeyError: 'text1'

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-32efc0807c9e> in <module>()
      1 questions = question1 + question2
----> 2 tokenizer = Tokenizer(nb_words=MAX_NB_WORDS)
      3 tokenizer.fit_on_texts(questions)
      4 question1_word_sequences = tokenizer.texts_to_sequences(question1)
      5 question2_word_sequences = tokenizer.texts_to_sequences(question2)

NameError: name 'Tokenizer' is not defined

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-75dc1a7a8812> in <module>()
      1 if not exists(KERAS_DATASETS_DIR + GLOVE_ZIP_FILE):
----> 2     zipfile = ZipFile(get_file(GLOVE_ZIP_FILE, GLOVE_ZIP_FILE_URL))
      3     zipfile.extract(GLOVE_FILE, path=KERAS_DATASETS_DIR)
      4 
      5 print("Processing", GLOVE_FILE)

NameError: name 'get_file' is not defined

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-7-3525c158fd6d> in <module>()
----> 1 q1_data = pad_sequences(question1_word_sequences, maxlen=MAX_SEQUENCE_LENGTH)
      2 q2_data = pad_sequences(question2_word_sequences, maxlen=MAX_SEQUENCE_LENGTH)
      3 labels = np.array(is_duplicate, dtype=int)
      4 print('Shape of question1 data tensor:', q1_data.shape)
      5 print('Shape of question2 data tensor:', q2_data.shape)

NameError: name 'pad_sequences' is not defined

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-8-7163ea96f4e1> in <module>()
----> 1 np.save(open(Q1_TRAINING_DATA_FILE, 'wb'), q1_data)
      2 np.save(open(Q2_TRAINING_DATA_FILE, 'wb'), q2_data)
      3 np.save(open(LABEL_TRAINING_DATA_FILE, 'wb'), labels)
      4 np.save(open(WORD_EMBEDDING_MATRIX_FILE, 'wb'), word_embedding_matrix)
      5 with open(NB_WORDS_DATA_FILE, 'w') as f:

NameError: name 'q1_data' is not defined

I tried to play in PyCharm IDE and Anaconda  Navigator adding necessary Frameworks like TensorFlow and Keras, NLP but still errors above seem like plug in didn't work well.

Really, appreciate your kind help and time.

Thanks and best regards

**Comment by MrKyaw** [comment]
Dear Bradely,

Also missing question_pairs_weights.h5 file and what is the purpose of for the following if you don't mind pls
1. keras-quora-question-pairs.py
2. quora-question-pairs-training.ipynb
3. quora-question-pairs-data-prep.ipynb

Best wishes

**Comment by bradleypallen** [comment]
MrKyaw- The .npy and .json files you are missing are created by executing the quora-question-pairs-data-prep.ipynb notebook. Once that is done, the various files will exist in the local directory. The .h5 is created as a side effect of executing the quora-question-pairs-training.ipynb notebook.
The keras-quora-question-pairs.py does the same work as if you had executed both notebooks in sequence. - regards, BPA
